const te=new TextEncoder();
const apiBase=e=>String(e.IYZICO_BASE_URL||'https://api.iyzipay.com').replace(/\/$/,'');
const plans=e=>({starter:String(e.IYZICO_PLAN_STARTER||''),pro:String(e.IYZICO_PLAN_PRO||''),business:String(e.IYZICO_PLAN_BUSINESS||'')});
const ready=e=>{const p=plans(e);return !!e.IYZICO_API_KEY&&!!e.IYZICO_SECRET_KEY&&!!p.starter&&!!p.pro&&!!p.business};
const j=(b,s=200,h={})=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}});
const hx=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const b64=b=>{let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s)};
async function auth(e,path,body=''){const rnd=`${Date.now()}${crypto.randomUUID().replace(/-/g,'').slice(0,10)}`;const k=await crypto.subtle.importKey('raw',te.encode(String(e.IYZICO_SECRET_KEY)),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=hx(await crypto.subtle.sign('HMAC',k,te.encode(rnd+path+body)));const raw=`apiKey:${e.IYZICO_API_KEY}&randomKey:${rnd}&signature:${sig}`;return{Authorization:`IYZWSv2 ${b64(te.encode(raw))}`,'x-iyzi-rnd':rnd,'Content-Type':'application/json',Accept:'application/json'}}
async function post(e,path,payload){const body=JSON.stringify(payload),r=await fetch(apiBase(e)+path,{method:'POST',headers:await auth(e,path,body),body}),d=await r.json().catch(()=>({}));if(!r.ok||d.status==='failure')throw Object.assign(new Error(d.errorMessage||d.errorCode||`iyzico hatası (${r.status})`),{status:r.status||502});return d}
async function get(e,path){const r=await fetch(apiBase(e)+path,{headers:await auth(e,path,'')}),d=await r.json().catch(()=>({}));if(!r.ok||d.status==='failure')throw Object.assign(new Error(d.errorMessage||d.errorCode||`iyzico hatası (${r.status})`),{status:r.status||502});return d}
async function sign(e,payload){const raw=btoa(unescape(encodeURIComponent(JSON.stringify(payload)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');const k=await crypto.subtle.importKey('raw',te.encode(String(e.IYZICO_SECRET_KEY)),{name:'HMAC',hash:'SHA-256'},false,['sign']);const s=b64(await crypto.subtle.sign('HMAC',k,te.encode(raw))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');return raw+'.'+s}
async function verify(e,t){if(!e.IYZICO_SECRET_KEY||!String(t||'').includes('.'))return null;const[a,s]=String(t).split('.',2),k=await crypto.subtle.importKey('raw',te.encode(String(e.IYZICO_SECRET_KEY)),{name:'HMAC',hash:'SHA-256'},false,['sign']);const ex=b64(await crypto.subtle.sign('HMAC',k,te.encode(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');if(s!==ex)return null;try{const pad=a.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-a.length%4)%4),d=JSON.parse(decodeURIComponent(escape(atob(pad))));return d.status==='active'&&Number(d.expiresAt)>Date.now()?d:null}catch{return null}}
const red=u=>new Response(null,{status:302,headers:{Location:u,'Cache-Control':'no-store'}});
export async function handleBilling(req,e,u){const path=u.pathname.replace(/\/+$/,'')||'/';
 if(path==='/billing/config'&&req.method==='GET')return j({ok:true,provider:'iyzico',configured:ready(e),mode:apiBase(e).includes('sandbox')?'sandbox':'production'});
 if(path==='/billing/initialize'&&req.method==='POST'){if(!ready(e))return j({ok:false,error:'iyzico henüz yapılandırılmadı.'},503);const b=await req.json().catch(()=>({})),plan=String(b.plan||''),ref=plans(e)[plan];if(!ref)return j({ok:false,error:'Geçersiz plan.'},400);if(!b.customer||typeof b.customer!=='object')return j({ok:false,error:'Müşteri bilgileri gerekli.'},400);const r=await post(e,'/v2/subscription/checkoutform/initialize',{locale:'tr',callbackUrl:`${u.origin}/billing/callback`,pricingPlanReferenceCode:ref,subscriptionInitialStatus:'ACTIVE',conversationId:crypto.randomUUID(),customer:b.customer});if(!r.token||!r.checkoutFormContent)return j({ok:false,error:'Ödeme formu oluşturulamadı.'},502);return j({ok:true,token:r.token,checkoutFormContent:r.checkoutFormContent,expiresIn:r.tokenExpireTime||1800});}
 if(path==='/billing/callback'&&req.method==='POST'){if(!ready(e))return red(`${u.origin}/?payment=error&reason=config`);const f=await req.formData().catch(()=>null),token=String(f?.get('token')||'');if(!token)return red(`${u.origin}/?payment=error&reason=token`);try{const r=await get(e,`/v2/subscription/checkoutform/${encodeURIComponent(token)}`),d=r.data||{};if(String(d.subscriptionStatus||'').toUpperCase()!=='ACTIVE')return red(`${u.origin}/?payment=error&reason=status`);const p=Object.entries(plans(e)).find(([,v])=>v===d.pricingPlanReferenceCode)?.[0]||'pro';const ent=await sign(e,{status:'active',plan:p,subscriptionReferenceCode:d.referenceCode||'',customerReferenceCode:d.customerReferenceCode||'',startedAt:Number(d.startDate||Date.now()),expiresAt:Number(d.endDate||Date.now()+35*86400000)});return red(`${u.origin}/?payment=success&plan=${encodeURIComponent(p)}&entitlement=${encodeURIComponent(ent)}`)}catch{return red(`${u.origin}/?payment=error&reason=verify`)}}
 if(path==='/billing/verify'&&req.method==='POST'){const b=await req.json().catch(()=>({})),d=await verify(e,b.entitlement);return j(d?{ok:true,active:true,subscription:d}:{ok:true,active:false})}
 return j({ok:false,error:'Billing endpoint bulunamadı.'},404)}
